### ISSUE TITLE
Remove width limit on the tree view

### ISSUE THREAD

**Issue by CaledoniaProject** [hasherezade/pe-bear-releases#13]
It looks like you set a maximum width on the tree view. It's too narrow on scaled screens:

![screenshot 2020-02-08 at 1 56 20 PM](https://user-images.githubusercontent.com/1357701/74080058-e5cb6880-4a7a-11ea-806e-b4ea13fd9ee9.jpg)

**Comment by CaledoniaProject** [comment]
It's already at its maximum allowed width, the bar in the middle is not draggable to the right.

**Comment by hasherezade** [comment]
Thank you for reporting, I will take care of this soon!

**Comment by hasherezade** [comment]
@CaledoniaProject  - this problem should be fixed in the latest release, please check if this is what you expected: https://github.com/hasherezade/pe-bear-releases/releases/tag/0.4.0.2

**Comment by CaledoniaProject** [comment]
Looks good to me
