### ISSUE TITLE
Linux compilation for libqt5

### ISSUE THREAD

**Issue by vmsv** [hasherezade/pe-bear-releases#18]
Hi, are you planing on releasing a version compiled with libqt5 for compatibility with Ubuntu 20.04?

**Comment by hasherezade** [comment]
Hi! Yes, this definitively will be done in upcoming months. Currently I am too busy with other things, but the refactoring to Qt5 is almost done. It just needs fixing some of the GUI elements, and some more testing. As long as I will be done with my current deadlines, I will take care of this.

**Comment by hasherezade** [comment]
Check the latest release! It is refactored to Qt5: https://github.com/hasherezade/pe-bear-releases/releases/tag/0.5.0

**Comment by vmsv** [comment]
Thx. Great work

**Comment by hasherezade** [comment]
Feel free to close this issue once you confirmed that everything works fine.

**Comment by vmsv** [comment]
Works perfectly.
