### ISSUE TITLE
Display PE structure data organization

### ISSUE THREAD

**Issue by qwertzy-qwertzy-qwertzy** [hasherezade/pe-bear-releases#25]
Would be great if PE Bear would display how the PE file data is organized in a visual manner. Example from Portex:
![portex_example_pe_structure](https://user-images.githubusercontent.com/74644600/99876117-8cd55700-2bec-11eb-827e-34a4715c1ebd.png)
Example from ghidra:
![ghidra_example_pe_structure](https://user-images.githubusercontent.com/74644600/99876159-cad27b00-2bec-11eb-835f-061c3108fc8a.png)

**Comment by hasherezade** [comment]
I think in PE-bear, the best fit could be to add the entrypy view as an alternative mode on the side view:

![side_view](https://user-images.githubusercontent.com/3115348/99898878-53aced80-2ca5-11eb-8b0b-c4a018b10613.png)

For now it shows sections, but I could add a context menu that would switch it into an entropy diagram. What do you think?

**Comment by qwertzy-qwertzy-qwertzy** [comment]
That would be great, thank you. Could you make the slider movable? at the moment its position seems to be set to fixed and if I increase the font size the labels get cut
![slider](https://user-images.githubusercontent.com/74644600/99903315-8530b380-2cbb-11eb-81ab-823df0bae8bb.png)

**Comment by hasherezade** [comment]
which version are you using? and on which OS?
I am using 0.5.2.2 and cannot reproduce the problem you described. Even with very big font size (39) I had no such problem.

![supersized](https://user-images.githubusercontent.com/3115348/99905348-8e784b00-2cd0-11eb-8f23-a9f1409f1695.png)

**Comment by hasherezade** [comment]
But I guess it may be some detail about wider font that I overlooked. I will check it, and fix scaling with the next release.

**Comment by qwertzy-qwertzy-qwertzy** [comment]
PE-Bear: 0.5.2.2
OS: Ubuntu 20.04

I think the issue is with the font itself: Free Pixel Regular, size 12, URL: https://fonts2u.com/free-pixel-regular.font 
with Ubuntu Regular it is just fine. I'll close the issue
![font_ok](https://user-images.githubusercontent.com/74644600/99906201-b0240300-2ccd-11eb-84f1-f11ea6424f18.png)

**Comment by hasherezade** [comment]
ok, anyways thanks for the headsup. some fonts are atypical, I tested with the ones that I had. anyways, giving it a bit more margin won't harm, so I will do it next time.
