### ISSUE TITLE
not working with a PE build by fasm 

### ISSUE THREAD

**Issue by catafest** [hasherezade/pe-bear-releases#29]
The file for test was build with [fasm](https://flatassembler.net/) 
```
[mythcat@desk fasm]$ file pe_001.exe 
pe_001.exe: PE32 executable (console) Intel 80386, for MS Windows
```
The result is a crash :
```
[mythcat@desk PE-bear_0.5.2.3_x64_linux]$ ./PE-bear 
"/proc/11817/root"
Segmentation fault (core dumped)
```

**Comment by hasherezade** [comment]
Thank you for reporting. Can you please attach (or send me via e-mail) the exact PE that caused the crash?

**Comment by hasherezade** [comment]
Thank you for your e-mail I checked the package that you sent:

[wetransfer-d6d2e4.zip](https://github.com/hasherezade/pe-bear-releases/files/5747743/wetransfer-d6d2e4.zip)

However, I cannot reproduce the error. On my side, the PE opened with no errors:

![pebear_screen](https://user-images.githubusercontent.com/3115348/103223368-5cd54e00-4926-11eb-8ee6-ac76c7b78fe0.png)

I tried on Linux and on Windows, zero issues.

I suspect that the reason of the crash may be caused by a different Qt version that you possibly use.
Could you please check your Qt version?
Any more details regarding your OS?

**Comment by hasherezade** [comment]
also, try to update your Qt and let me know if it helps.

**Comment by catafest** [comment]
```
[mythcat@desk fasm]$ uname -a
Linux desk 5.9.16-200.fc33.x86_64 #1 SMP Mon Dec 21 14:08:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

[mythcat@desk fasm]$ pkg-config --modversion QtCore
Package QtCore was not found in the pkg-config search path.
Perhaps you should add the directory containing `QtCore.pc'
to the PKG_CONFIG_PATH environment variable
Package 'QtCore', required by 'virtual:world', not found

[mythcat@desk fasm]$ qmake-qt5 --version
QMake version 3.1
Using Qt version 5.15.2 in /usr/lib64

maybe is video card problem 
NVIDIA Corporation GT218 [GeForce 210]
```

**Comment by hasherezade** [comment]
I don't think your video card could be a problem, rather different versions of libraries than those with which the PE-bear's binary was compiled.
Did you experience similar crashes on load of other executables as well, or only with those that are compiled with fasm?

**Comment by catafest** [comment]
I think you need to create a bash sh file for each project.
Also, you need to put the libs used this sh or to tell people how libs need to used. 
The idea to scan files and check them has a good format is great.

**Comment by hasherezade** [comment]
Can you check this? I added my Qt to the package, let's see if it helps:

[PE-bear_0.5.2.3_test.tar.gz](https://github.com/hasherezade/pe-bear-releases/files/5754185/PE-bear_0.5.2.3_test.tar.gz)

**Comment by hasherezade** [comment]
It seems to be the same issue as here: https://github.com/hasherezade/pe-bear-releases/issues/34
Please let me know if the build with **Qt 5.14** works fine for you. It is this one:

https://github.com/hasherezade/pe-bear-releases/releases/download/0.5.4/PE-bear_0.5.4_qt5.14_x64_linux.tar.xz

**Comment by hasherezade** [comment]
From now you can build PE-bear from the sources to avoid any of such issues: https://github.com/hasherezade/pe-bear
