### ISSUE TITLE
Feature Request: File->New Window

### ISSUE THREAD

**Issue by trufae** [hasherezade/pe-bear-releases#37]
Instead of having to run the tool again, and maybe bind that to a key combination to not depend on the mouse.

**Comment by hasherezade** [comment]
Please have a look at the test build, and let me know if this is what you mean:

+ [PE-bear_0.5.4.1-c_x64_win_vs13.zip](https://github.com/hasherezade/pe-bear-releases/files/7598759/PE-bear_0.5.4.1-c_x64_win_vs13.zip)

**Comment by trufae** [comment]
Works as expected! thanks!
