### ISSUE TITLE
Feature Request: Detect when the file in disk has changed and ask the user to reload it

### ISSUE THREAD

**Issue by trufae** [hasherezade/pe-bear-releases#38]

**Comment by hasherezade** [comment]
Hi! I implemented this feature, would you like to test it?
Here is the build:

[PE-bear_0.5.4.1-a_x64_win_vs13.zip](https://github.com/hasherezade/pe-bear-releases/files/7523839/PE-bear_0.5.4.1-a_x64_win_vs13.zip)

There is an option in Settings that allows to regulate if the file should be reloaded automatically, or show a popup:

![configure_reload](https://user-images.githubusercontent.com/3115348/141384648-95ed78a3-e072-4272-9890-91d9a1d5ff9f.png)

**Comment by hasherezade** [comment]
I implemented this feature, please have a look at the builds and let me know what do you think:
+ [PE-bear_0.5.4.1-a_x64_win_vs13.zip](https://github.com/hasherezade/pe-bear-releases/files/7523906/PE-bear_0.5.4.1-a_x64_win_vs13.zip)
+ [PE-bear_0.5.4.1-a_x86_win_vs13.zip](https://github.com/hasherezade/pe-bear-releases/files/7523907/PE-bear_0.5.4.1-a_x86_win_vs13.zip)

You can change in the settings whether the file should reload automatically, or display a popup:

![configure_reload](https://user-images.githubusercontent.com/3115348/141386157-14d34b72-bf99-4b6c-9999-6be39d8fed70.png)

There is an issue with reloading the files from shared directories in the situation described here:
+ https://forum.qt.io/topic/87578/issue-with-qfilesystemwatcher-in-linux-system-with-directory-shared-by-windows-using-cifs-protocol

but unfortunately for now I don't know how to resolve it.

**Comment by hasherezade** [comment]
Hi, sorry for the delay - I was busy with other things. But I think I fixed it now. Please have a look at the new version:

+ [PE-bear_0.5.4.1-b_x64_win_vs13.zip](https://github.com/hasherezade/pe-bear-releases/files/7590243/PE-bear_0.5.4.1-b_x64_win_vs13.zip)

**Comment by trufae** [comment]
I can confirm it works well now :) no double reloads!
