### ISSUE TITLE
Feature Request: Load multiple files using CLI and File->Open dialog

### ISSUE THREAD

**Issue by droberson** [hasherezade/pe-bear-releases#39]
PE-Bear allows you to specify a file to load from a prompt. Specifying more than one file only opens the first specified:

    % PE-bear one.exe
    % PE-bear one.exe two.exe three.exe    #### Only loads one.exe

Multiple files can be subsequently opened using File->Load PE or Control+O, but this dialog also appears to support loading one file at a time, which can become tedious when working with sets of files.

Please consider adding functionality to load multiple files at the same time.

If it helps, this is the version I am using:

PE-bear - Portable Executable reversing tool
version: 0.5.4 Qt5
built on: May 24 2021

**Comment by hasherezade** [comment]
Thank you, this is a good idea, I will add a support for a list of files supplied from a commandline.

I don't know if you noticed, but you can also drag and drop multiple files at the same time, and all of them will be loaded.

**Comment by hasherezade** [comment]
I added it in the new release - please check it out:
https://github.com/hasherezade/pe-bear-releases/releases/tag/0.5.5

**Comment by droberson** [comment]
works great. thank you very much!
