### ISSUE TITLE
Discrepancy in PDB GUID Value

### ISSUE THREAD

**Issue by xorhex** [hasherezade/pe-bear-releases#40]
Sample: https://malshare.com/sample.php?action=detail&hash=53a8a63c14bb562ab71bf2283f10e3ed23717f7393aa3f6f8eb213ac48465769

The value shown in the RSDS table (GUID) at the bottom aren't matching the values in the hex display at the top.

![debug_guid_discrepancy](https://user-images.githubusercontent.com/40742023/143796233-d468a2bd-f450-4abf-99c6-0110a1b25ba8.png)

**Comment by hasherezade** [comment]
Thank you for reporting! Indeed there was an error in formatting of the string. I fixed it:

![pebear_fixed](https://user-images.githubusercontent.com/3115348/143898263-c1a6207c-8848-4db4-9384-eb182f014aaf.png)

It will be included in the next release.

**Comment by hasherezade** [comment]
@xorhex - please check out the new release: https://github.com/hasherezade/pe-bear-releases/releases/tag/0.5.5.1

**Comment by hasherezade** [comment]
@xorhex - feel free to close this issue once you are sure that it works as expected.

**Comment by hasherezade** [comment]
huh, I comparing it with the GUID displayed on VT, I see that still I got the endianness of one of the chunks wrong:
![pdb_filpped](https://user-images.githubusercontent.com/3115348/149632101-ea502afa-96c2-450f-83e7-25bbfc5d0208.png)
what I display as `F590` should be `90F5`.
I am gonna doublecheck it with other tools and fix it today.

**Comment by hasherezade** [comment]
@xorhex - updated: https://github.com/hasherezade/pe-bear-releases/releases/tag/0.5.5.2 - now it should be ok
