### ISSUE TITLE
Compilation for ARM64

### ISSUE THREAD

**Issue by vysecurity** [hasherezade/pe-bear-releases#46]
Hi there, right now the release is using Intel MacOS, can we compile it for ARM64?

**Comment by hasherezade** [comment]
hi @vysecurity ! 
yes, it is possible. I added [a build for ARM 32-bit](https://github.com/hasherezade/pe-bear-releases/releases/download/0.5.5.5/PE-bear_0.5.5.5_qt5.7_arm32.tar.xz), later I will also add a build for ARM64.

**Comment by vysecurity** [comment]
Sure!

**Comment by hasherezade** [comment]
@vysecurity - I added a build for ARM64, please check it out:
https://github.com/hasherezade/pe-bear-releases/releases/download/0.5.5.5/PE-bear_0.5.5.5_qt5.15_arm64.tar.xz

**Comment by hasherezade** [comment]
@vysecurity - from now PE-bear is open source, so you can build it for the platform of your choice: https://github.com/hasherezade/pe-bear
