### ISSUE TITLE
Saving executable in pe-bear corrupts its icon

### ISSUE THREAD

**Issue by not6** [hasherezade/pe-bear-releases#50]
seems to happen to every executable i try including pe-bear itself
how to replicate: open exe in pe-bear then save it, nothing else has to be done, no options have to be changed

a byte in the resource directory is changed for no apparent reason, causing this strange effect

examples:
![Example 1](https://i.imgur.com/dtedcUV.png)
![Example 2](https://i.imgur.com/tjk1G0D.png)

**Comment by hasherezade** [comment]
hi @not6 !
you are right. thank you for reporting. it will be fixed in the upcoming release.

**Comment by hasherezade** [comment]
@not6 - I fixed this bug and made a test build for you. please let me know if everything is fine now:
+ [PE-bear_0.5.5.6-rc2_x64_win_vs17.zip](https://github.com/hasherezade/pe-bear-releases/files/9463534/PE-bear_0.5.5.6-rc2_x64_win_vs17.zip)

I will ping you when the official release is ready.

**Comment by not6** [comment]
> @not6 - I fixed this bug and made a test build for you. please let me know if everything is fine now:
> 
>     * [PE-bear_0.5.5.6-rc2_x64_win_vs17.zip](https://github.com/hasherezade/pe-bear-releases/files/9463534/PE-bear_0.5.5.6-rc2_x64_win_vs17.zip)
> 
> 
> I will ping you when the official release is ready.

sorry for the late-ish response, i have tried your build and it's working perfectly. thank you!

**Comment by hasherezade** [comment]
@not6 - thanks for checking! I am glad that all works fine now. feel free to ping me anytime if you notice that something is not ok.

**Comment by hasherezade** [comment]
@not6 - check out the new release: https://github.com/hasherezade/pe-bear-releases/releases/tag/0.5.5.7

**Comment by not6** [comment]
just did a couple tests and it works perfectly! thank you and sorry i couldn't have checked earlier
