### ISSUE TITLE
malformed PE prevents from bearparser to locate the imports

### ISSUE THREAD

**Issue by Dor00tkit** [hasherezade/pe-bear-releases#9]
NOTE: I discovered this trick when i was dealing with an old crackme (2004) written by Nicolas Brulez.

The trick will prevent PE-bear (that using bearparser) (and many other tools) to correctly parsing the Imports.

In the case that the last section of the PE file is the section where the Imports are residing, we can perform the following steps:

1. Create a new section (named _new_imp_).

2. Set the fields of the new section header to overlap with the original (named _org_imp_) fields of import section (except "_VirtualAddress_").

3. Set the _SizeOfRawData_ field of the original Imports section (named org_imp) to abnormal value like _0xDEADC0DE_.

4. (**_Optional_**) Update the _ImportDirectory_ fields containing RVA (e.g: _OriginalFirstThunk_, _Name_, _FirstThunk_) to point to the new section.

5. Update the _DataDirectories.ImportDirectory.VA_ to point to the new imports section.

**OR:**

4.  Update the _ImportDirectory_ fields containing RVA (e.g: _OriginalFirstThunk_, _Name_, _FirstThunk_) to point to the new section.

5. (**_Optional_**)Update the _DataDirectories.ImportDirectory.VA_ to point to the new imports section.

![pebear failed](https://user-images.githubusercontent.com/47893732/63329510-c3ae2480-c33a-11e9-861e-1ff364038001.JPG)

**Comment by hasherezade** [comment]
ok, it should work fine in the latest release: [0.3.9.7](https://github.com/hasherezade/pe-bear-releases/releases/tag/0.3.9.7) of PE-bear. 
![pebear_fixed](https://user-images.githubusercontent.com/3115348/69019366-9d873780-09b0-11ea-88ca-8175a42a24f3.png)
Please check it out. Thank you for your contribution!
